server:
  port: 8762
spring:
  application:
    name: torrent-download-service
  redis:
    host: 127.0.0.1
    port: 6379
    jedis:
      pool:
        max-idle: 1000
        min-idle: 0
        max-active: 1000
        max-wait: -1ms
  cloud:
    stream:
      kafka:
        binder:
          brokers: 127.0.0.1
          auto-add-partitions: true
          min-partition-count: 1
          configuration:
            max.request.size: 12048576
      bindings:
        download-in-0:
          group: download-group
          destination: download-topic
          contentType: application/json
          consumer:
            max-poll-records: 3000
            batch-mode: true
            compressionType: gzip
        download-out-0:
          destination: store-topic
          contentType: application/json
          producer:
            partitionCount: 1             # 大于等于 store service 集群数量
            useNativeEncoding: true
            compressionType: gzip

management:
  endpoints:
    web:
      exposure:
        include: ["*"]

download:
  num:
    thread: 3000
  enable-filter-sensitive-words: true     #是否开启过滤敏感词

logging:
  level:
    root: info