server:
  port: 8762
spring:
  application:
    name: torrent-download-service
  redis:
    host: 127.0.0.1
    port: 6379
    jedis:
      pool:
        max-idle: 1000
        min-idle: 0
        max-active: 1000
        max-wait: -1ms
  cloud:
    stream:
      kafka:
        binder:
          brokers: 127.0.0.1
          min-partition-count: 1
      bindings:
        handle-in-0:
          group: torrent-download-group
          destination: downloadMessages
          contentType: application/json
          consumer:
            max-poll-records: 500
            batch-mode: true
            compressionType: gzip
        handle-out-0:
          destination: torrentMessages
          contentType: application/json
          producer:
            compressionType: gzip
  kafka:
    bootstrap-servers: 127.0.0.1:9092
    consumer:
      auto-offset-reset: earliest

feign:
  httpclient:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: ["*"]

download:
  num:
    thread: 2500
  enable-filter-sensitive-words: true     #是否开启过滤敏感词