server:
  port: 8100
## netty服务器端口
netty:
  udp:
    port: 6688
  so:
    rcvbuf: 268435456
    sndbuf: 65536

spring:
  redis:
    host: 149.56.240.89
    port: 16379
    password: '!@#123QweAsdZxc0.123456RTyFGh'
    #password: 123456
    jedis:
      pool:
        max-idle: 8
        min-idle: 0
        max-active: 8
        max-wait: -1ms

download:
  num:
    thread: 3000
  enable-filter-sensitive-words: true     #是否开启过滤敏感词

logging:
  level:
    root: debug