server:
  port: 8764
spring:
  application:
    name: torrent-store-service
  cloud:
    stream:
      kafka:
        binder:
          brokers: 127.0.0.1
      bindings:
        handle-in-0:
          group: torrent-store-group
          destination: torrentMessages
          contentType: application/json
          consumer:
            batch-mode: true
            max-poll-records: 500
            compressionType: gzip
            autoCommitOffset: false #设置手动提交偏移
  kafka:
    bootstrap-servers: 127.0.0.1:9092
    consumer:
      auto-offset-reset: earliest
  elasticsearch:
    rest:
      uris: 127.0.0.1:9200
#  main:
#    allow-bean-definition-overriding: true
dubbo:
  protocol:
    name: dubbo
    port: 23456
  registry:
    address: N/A
  scan:
    base-packages: cc.dodder.torrent.store.api.impl
store:
  service:
    version: 1.0.0
dodder:
  filter-sensitive-torrent: true  #开启过滤敏感资源
logging:
  level:
    root: info